### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by arretx** [wxt9861/ynab#28]
The sensor works!  However, after 24 hours, there were no changes to the state, which I know would not be true.

So, I'm wondering how the update system works and if the YNAB account is queried regularly or not.  Today, the moment I logged into my YNAB account, the sensor in Home Assistant updated...but the whole reason I was seeking out this type of integration was to have HA notify me when there was something new on YNAB.

This makes me wonder if YNAB only processes bank imports upon user login, in which case, there's no way to fully automate notification of new transactions.  

Thoughts?  By the way, thanks for the integration, aside from this hiccup, it's really cool to be able to integrate this data into the UI in HA.

**Comment by guitarwiz09** [comment]
I have the same issue. Tried manually triggering a refresh but hard to test if that is working. Any suggested work arounds? I works when I pull it up on web or the app.

**Comment by arretx** [comment]
I'm using NodeRED to trigger an HTTP Post request to the /transactions/import endpoint that YNAB publishes.  It seems that they haven't made this available in the Python api which the author of this integration mentioned...so it's the only workaround I have found, but it works to make sure the sensor is updated regularly.

**Comment by wxt9861** [comment]
Since python ynab api does not have an improt endpoint I added ability to request an import using the component. It should now send a post call to the API every time it updates (5 min interval).

You can test it using [v0.3.0b](https://github.com/wxt9861/ynab/releases/tag/v0.3.0b) release. If you have debugging enabled, you'll be able to see how many transactions were imported as well as current API usage.

**Comment by wxt9861** [comment]
Addressed by #30
